- name: groupadd law
  tags: user
  group: name=law state=present

- name: useradd law
  tags: user
  user: >
    name=law
    comment='Lee Whalen'
    group=law
    groups="adm, sudo"
    state=present

- name: add law's ssh keys
  tags: user
  authorized_key: >
    user=law
    key="{{ lookup('file', 'ssh/{{ env }}/{{ item.file }}') }}"
    state=present
  with_items:
    - { file: 'law-20210116.pub' }

#- name: revoke law's ssh keys
#  tags: user
#  authorized_key: >
#    user=law
#    key="{{ lookup('file', 'ssh/{{ env }}/{{ item.file }}') }}"
#    state=absent
#  with_items:
#    - { file: 'law-20210116.pub' }
