---
- name: lobsters
  tags: lobsters
  become: yes
  hosts: www_worker
  roles:
    - { role: lobsters }

- name: puma
  tags: puma
  become: yes
  hosts: www_worker
  roles:
    - { role: puma }

- name: nginx
  tags: nginx
  become: yes
  hosts: www
  roles:
    - { role: nginx }

- name: postfix
  tags: postfix
  become: yes
  hosts: mx:smtp
  roles:
    - { role: postfix }

- name: lobstersbot
  tags: lobstersbot
  become: yes
  hosts: lobstersbot
  roles:
    - { role: lobstersbot }

- name: sysadm
  tags: sysadm
  become: yes
  hosts: all
  roles:
    - { role: sysadm }

- name: tarsnap
  tags: tarsnap
  become: true
  hosts: all:!mockturtle
  roles:
    - { role: tarsnap,
        # don't back up the test system.
        when: "env == 'production'"
      }
